pagespeed:
  env_file: configs/local/${SITE}/.config.env
  build: docker/pagespeed
  ports:
    - "80"
    - "8080"
  links:
    - memcached:memcached

nginx:
  build: docker/nginx
  ports:
    - "80:80"
  links:
    - pagespeed:pagespeed
 

memcached:
   image: memcached
   ports:
    - "11211:11211"